<?php

return array_replace_recursive([
    'en' => [
        'about' => [
            'page_title' => 'About Industrialmac',
            'headline' => 'Your Global Partner for Industrial Supply',
            'intro' => [
                'Industrialmac is an international supplier of industrial spare parts, automation components, MRO products, tools, and technical solutions for manufacturers and industrial businesses worldwide.',
                'Our mission is simple: to help companies keep their production running by providing reliable products, technical expertise, and fast, efficient service.',
                'We understand that every production line depends on the availability of the right components at the right time. That\'s why we work every day to simplify procurement, reduce downtime, and support our customers with solutions tailored to their operational needs.',
            ],
            'experience_title' => 'Our Experience',
            'experience' => [
                'Industrialmac was built on years of experience in the industrial sector and a deep understanding of manufacturing environments.',
                'Our team works closely with maintenance engineers, purchasing departments, production managers, and OEMs across multiple industries, supporting projects ranging from routine maintenance to complex industrial upgrades.',
            ],
            'what_we_do_title' => 'What We Do',
            'what_we_do_intro' => 'We specialize in the international sourcing and supply of:',
            'what_we_do' => [
                'Industrial Spare Parts',
                'Automation Components',
                'MRO (Maintenance, Repair & Operations) Products',
                'Industrial Tools and Equipment',
                'Electronic Components',
                'Pneumatic and Hydraulic Products',
                'Process and Production Solutions',
            ],
            'why_title' => 'Why Choose Industrialmac',
            'why' => [
                ['title' => 'Technical Expertise', 'text' => 'Our team combines commercial experience with technical knowledge, allowing us to recommend the right solution—not simply sell a product.'],
                ['title' => 'Global Supply Network', 'text' => 'We collaborate with an extensive network of manufacturers and authorized suppliers, giving our customers access to thousands of industrial products from leading international brands.'],
                ['title' => 'Fast & Flexible Service', 'text' => 'Industrial production cannot wait. We are committed to responding quickly, offering efficient sourcing solutions and reliable delivery to minimize downtime.'],
                ['title' => 'Customer-Focused Approach', 'text' => 'Every customer has different requirements. We listen, understand, and build long-term partnerships based on trust, transparency, and consistent support.'],
                ['title' => 'Quality & Reliability', 'text' => 'We carefully select our suppliers and partners to ensure that every product meets the quality and performance standards expected by modern industry.'],
            ],
            'vision_title' => 'Our Vision',
            'vision' => 'To become a trusted global reference for industrial supply by connecting businesses with reliable products, technical expertise, and innovative sourcing solutions.',
            'mission_title' => 'Our Mission',
            'mission' => 'Our mission is to support industrial companies with dependable products, responsive service, and expert technical assistance.',
            'values_title' => 'Our Values',
            'values' => [
                ['title' => 'Reliability', 'text' => 'We believe that trust is earned through consistency, transparency, and delivering on our commitments.'],
                ['title' => 'Expertise', 'text' => 'We continuously develop our technical knowledge to provide valuable support and practical solutions for our customers.'],
                ['title' => 'Partnership', 'text' => 'We work alongside our customers, building long-term relationships based on collaboration and mutual success.'],
                ['title' => 'Efficiency', 'text' => 'We simplify sourcing, reduce complexity, and provide fast responses to keep industrial operations running smoothly.'],
                ['title' => 'Continuous Improvement', 'text' => 'Industrial technology evolves every day—and so do we. We continuously improve our services, processes, and supplier network to create greater value for our customers.'],
            ],
            'closing_title' => 'More Than a Supplier',
            'closing' => 'At Industrialmac, we believe that supplying industrial products is only part of our job. Our real value lies in helping customers solve problems, find alternatives, optimize procurement, and secure the components they need to keep their business operating efficiently.',
        ],
        'quality' => [
            'page_title' => 'Quality Policy',
            'headline' => 'Committed to Quality. Driven by Reliability.',
            'intro' => [
                'At Industrialmac, quality is more than a process—it is the foundation of everything we do.',
                'Every product we source, every supplier we select, and every customer we support reflects our commitment to delivering reliable industrial solutions that help businesses operate efficiently and confidently.',
            ],
            'commitment_title' => 'Our Commitment',
            'commitment' => 'Industrialmac is committed to providing products and services that consistently meet customer expectations through professionalism, technical expertise, and continuous improvement.',
            'principles_title' => 'Our Quality Principles',
            'principles' => [
                ['title' => 'Customer Satisfaction', 'text' => 'Our customers are at the center of every decision we make. We listen carefully to their requirements and provide solutions that support productivity, efficiency, and business continuity.'],
                ['title' => 'Reliable Supply', 'text' => 'We work with carefully selected manufacturers and trusted international partners to ensure the consistent availability of high-quality industrial products.'],
                ['title' => 'Technical Competence', 'text' => 'Our team combines commercial experience with technical knowledge to assist customers in selecting the most appropriate products for their applications.'],
                ['title' => 'Continuous Improvement', 'text' => 'We regularly review our internal processes, supplier performance, and customer feedback to improve quality at every level.'],
            ],
            'promise_title' => 'Our Promise',
            'promise' => 'At Industrialmac, we strive every day to deliver industrial solutions that our customers can trust—today and in the future.',
        ],
    ],
    'it' => [
        'about' => [
            'page_title' => 'Chi Siamo',
            'headline' => 'Il tuo partner globale per la fornitura industriale',
            'intro' => [
                'Industrialmac è un fornitore internazionale di ricambi industriali, componenti di automazione, prodotti MRO, utensili e soluzioni tecniche per aziende manifatturiere e industriali in tutto il mondo.',
                'La nostra missione è semplice: aiutare le aziende a mantenere la produzione attiva offrendo prodotti affidabili, competenza tecnica e un servizio rapido ed efficiente.',
            ],
            'experience_title' => 'La nostra esperienza',
            'experience' => [
                'Industrialmac nasce da anni di esperienza nel settore industriale e da una profonda conoscenza degli ambienti produttivi.',
            ],
            'what_we_do_title' => 'Cosa facciamo',
            'what_we_do_intro' => 'Ci specializziamo nell’approvvigionamento e nella fornitura internazionale di:',
            'what_we_do' => [
                'Ricambi industriali',
                'Componenti di automazione',
                'Prodotti MRO',
                'Utensili e attrezzature industriali',
                'Componenti elettronici',
                'Prodotti pneumatici e idraulici',
                'Soluzioni di processo e produzione',
            ],
            'why_title' => 'Perché scegliere Industrialmac',
            'why' => [
                ['title' => 'Competenza tecnica', 'text' => 'Il nostro team unisce esperienza commerciale e conoscenza tecnica per consigliare la soluzione giusta.'],
                ['title' => 'Rete di fornitura globale', 'text' => 'Collaboriamo con una vasta rete di produttori e fornitori per offrire migliaia di prodotti industriali.'],
                ['title' => 'Servizio rapido e flessibile', 'text' => 'Rispondiamo rapidamente con soluzioni di sourcing affidabili per ridurre i fermi macchina.'],
                ['title' => 'Approccio orientato al cliente', 'text' => 'Ascoltiamo, comprendiamo e costruiamo partnership a lungo termine basate su fiducia e trasparenza.'],
                ['title' => 'Qualità e affidabilità', 'text' => 'Selezioniamo con cura fornitori e partner per garantire standard qualitativi elevati.'],
            ],
            'vision_title' => 'La nostra visione',
            'vision' => 'Diventare un punto di riferimento globale per la fornitura industriale, collegando le imprese a prodotti affidabili e soluzioni di sourcing innovative.',
            'mission_title' => 'La nostra missione',
            'mission' => 'Supportare le aziende industriali con prodotti affidabili, servizio reattivo e assistenza tecnica specialistica.',
            'values_title' => 'I nostri valori',
            'values' => [
                ['title' => 'Affidabilità', 'text' => 'La fiducia si costruisce con coerenza, trasparenza e rispetto degli impegni.'],
                ['title' => 'Competenza', 'text' => 'Sviluppiamo continuamente la nostra conoscenza tecnica per offrire soluzioni pratiche.'],
                ['title' => 'Partnership', 'text' => 'Lavoriamo al fianco dei clienti costruendo relazioni di lungo periodo.'],
                ['title' => 'Efficienza', 'text' => 'Semplifichiamo il sourcing e riduciamo la complessità operativa.'],
                ['title' => 'Miglioramento continuo', 'text' => 'Miglioriamo continuamente servizi, processi e rete fornitori.'],
            ],
            'closing_title' => 'Più di un fornitore',
            'closing' => 'Il nostro vero valore è aiutare i clienti a risolvere problemi, trovare alternative, ottimizzare gli acquisti e garantire i componenti necessari alla continuità operativa.',
        ],
        'quality' => [
            'page_title' => 'Politica della Qualità',
            'headline' => 'Impegnati nella qualità. Guidati dall’affidabilità.',
            'intro' => [
                'In Industrialmac la qualità è più di un processo: è il fondamento di tutto ciò che facciamo.',
            ],
            'commitment_title' => 'Il nostro impegno',
            'commitment' => 'Industrialmac si impegna a fornire prodotti e servizi che soddisfino costantemente le aspettative dei clienti attraverso professionalità, competenza tecnica e miglioramento continuo.',
            'principles_title' => 'I nostri principi di qualità',
            'principles' => [
                ['title' => 'Soddisfazione del cliente', 'text' => 'I clienti sono al centro di ogni decisione.'],
                ['title' => 'Fornitura affidabile', 'text' => 'Lavoriamo con produttori e partner internazionali selezionati con cura.'],
                ['title' => 'Competenza tecnica', 'text' => 'Assistiamo i clienti nella scelta dei prodotti più adatti alle loro applicazioni.'],
                ['title' => 'Miglioramento continuo', 'text' => 'Analizziamo processi, fornitori e feedback per elevare la qualità a ogni livello.'],
            ],
            'promise_title' => 'La nostra promessa',
            'promise' => 'Ogni giorno ci impegniamo a offrire soluzioni industriali di cui i clienti possano fidarsi, oggi e in futuro.',
        ],
    ],
], require __DIR__ . '/company_es_ru.php');
